name: Apply

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Terraform version to run'
        default: '1.1.7'
        required: false
        type: string

      runs-on:
        description: 'Where to run, usually ubuntu-latest or self-hosted'
        default: 'ubuntu-latest'
        required: false
        type: string

  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform apply
        id: tf-apply
        env:
          TF_WORKSPACE: default
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Terraform plan
        id: tf-plan
        env:
          TF_WORKSPACE: default
        run: |
          terraform init
          terraform plan -detailed-exitcode
