name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan:
    name: Packer Release
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: push_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          RELEASE_BRANCHES: 'main'
          WITH_V: true

      - name: Test output
        env:
          TAG: ${{ steps.push_tag.new_tag }}
        run: |
          echo "tag is $TAG"
